### PR TITLE
Move build system to meson

### PR DESCRIPTION
**Pull request by sergio-correia**

### CODE REVIEW

**Comment by radosroka** [comment]
Hi Sergio, 
it looks good and it works for me but I spotted these two warnings in CI and I'm not sure if that's expected.

* WARNING: Consider using the builtin warning_level option instead of adding warning flags by hand.
* meson.build:82: WARNING: Will not build man pages due to missing a2x (asciidoc) dependency!

**Comment by sergio-correia** [comment]
> Hi Sergio,
> it looks good and it works for me but I spotted these two warnings in CI and I'm not sure if that's expected.
> 
>     * WARNING: Consider using the builtin warning_level option instead of adding warning flags by hand.
> 
>     * meson.build:82: WARNING: Will not build man pages due to missing a2x (asciidoc) dependency!

Thanks for taking a look!

Yeah, they were kind of expected, since I was using the jose project as a template :)
In any case, I have just pushed a new commit defining the warning_level in meson and also installing the missing `asciidoc` package in the CI, so these warnings should be gone.

**Comment by radosroka** [comment]
Now it works as expected.

**Comment by sergio-correia** [comment]
> Now it works as expected.

Thanks for the review. I will squash those commits and merge the PR.

**Pull request merged**
