### PR TITLE
Move key handling to tang itself

### PR DESCRIPTION
**Pull request by sergio-correia**
This effectively removes the cache directory -- usually /var/cache/tang
--, which had pre-computed files with signed advertisements and JWK with
keys for deriving new keys.

This computation was done by the tangd-update script, which has also
been removed in this commit.

We relied on systemd to run this script whenever the JWK dir -- usually
/var/db/tang, which is where the actual keys are located -- changed, to
keep the cache directory updated, but this is sometimes unreliable,
causing issues like the ones reported in #23 and #24.

As of now, tang performs these computations itself and does not depend
on external scripts to make sure it has reliable information regarding
its keys.

Tests added as well.

Resolves: #23
Resolves: #24

### CODE REVIEW

**Comment by cbiedl** [comment]
Not looking good on armhf, possibly still a race

    1/3 adv       TIMEOUT        90.13s
    
    --- command ---
    22:10:54 SD_ACTIVATE='/usr/bin/systemd-socket-activate --inetd' PATH='/<<PKGBUILDDIR>>/src:/<<PKGBUILDDIR>>/obj-arm-linux-gnueabihf/src:/usr/lib/ccache:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games' /<<PKGBUILDDIR>>/tests/adv
    --- stdout ---
    {"payload": "eyJrZXlzIjogW3siYWxnIjogIkVTNTEyIiwgImNydiI6ICJQLTUyMSIsICJrZXlfb3BzIjogWyJ2ZXJpZnkiXSwgImt0eSI6ICJFQyIsICJ4IjogIkFVLWZZc19HZHd5Q2g0N0tDOEU5U0tkWERxMU9nYU9CcVNiQ1JPMlNYN1JvMnBxWVoyZ0llZzBiRU9COFowTzk3TlJjcjFpLS12dHljTE9TQTNQaFBtY3AiLCAieSI6ICJBQVdjRXVsRlkxTGNTZzZJUk9xQ25DMkZIWW9tTEVrd2hkU3BhTDlXZTJvUi1RY1l4a1RobFcxb01NX2loR1lVc3Z6cnhXeVdWd2Ewa191LWpSYmdNa2p3In0sIHsiYWxnIjogIkVDTVIiLCAiY3J2IjogIlAtNTIxIiwgImtleV9vcHMiOiBbImRlcml2ZUtleSJdLCAia3R5IjogIkVDIiwgIngiOiAiQUV1Mjd5dm9KUjNxN2xHaDY1VFBNZWxzMy1Rc3hxTmJRajA3SzQxMkJlVjlxRzFuODhYX1hhSV9wQTMxTU1Ua2prV2pSbW8yMnhOX3YwRi1jVjBvZjk3YSIsICJ5IjogIkFjMkNvRnQ2X19uR1pXam9GamFwdWYyOEdpY29HaTJWaDVOc3JsYjBkQ1BMOW12VlFOMVFjaWNueUNhd2hGUW9KcGxXUmtVYWstSkZpczdLaVlaRWVENnkifV19", "protected": "eyJhbGciOiJFUzUxMiIsImN0eSI6Imp3ay1zZXQranNvbiJ9", "signature": "AFmazBHspqbzUUIrSbRA5NiIB1ePk1K69bFcuCbMZ0QHfeGv7GlsWrd6Y78I464pPYuYGTL6StQ_ojTrvZcbR3hGAAf18u7KesoT0efZhbgYqd0UU3ZqmYyLZrbztjPT2Pfua2xDVPPF-L_rpYxoZXnu9FPyW69a4W1HmKcwaJxzGV_3"}
    --- stderr ---
    + trap on_exit EXIT
    + trap exit ERR
    ++ mktemp -d
    + export TMP=/tmp/tmp.gwHry8iGOS
    + TMP=/tmp/tmp.gwHry8iGOS
    + mkdir -p /tmp/tmp.gwHry8iGOS/db
    + tangd-keygen /tmp/tmp.gwHry8iGOS/db sig exc
    + jose jwk gen -i '{"alg": "ES512"}' -o /tmp/tmp.gwHry8iGOS/db/.sig.jwk
    + jose jwk gen -i '{"alg": "ES512"}' -o /tmp/tmp.gwHry8iGOS/db/.oth.jwk
    ++ shuf -i 1024-65536 -n 1
    + export PORT=50243
    + PORT=50243
    + export PID=301670
    + PID=301670
    + sleep 0.5
    + /usr/bin/systemd-socket-activate --inetd -l 127.0.0.1:50243 -a tangd /tmp/tmp.gwHry8iGOS/db
    Listening on 127.0.0.1:50243 as 3.
    + fetch /
    + curl -sfg http://127.0.0.1:50243/
    Communication attempt on fd 3.
    Connection from 127.0.0.1:57526 to 127.0.0.1:50243
    Spawned tangd (tangd /tmp/tmp.gwHry8iGOS/db) as PID 301678.
    Execing tangd (tangd /tmp/tmp.gwHry8iGOS/db)
    <unknown> GET / => 404 (../src/http.c:128)
    Child 301678 died with code 0
    (...)

Will check further and report.

**Comment by cbiedl** [comment]
Not looking good on armhf. Test suite fails

    <unknown> GET / => 404 (../src/http.c:128)

Will check further, stay tuned.

**Comment by sergio-correia** [comment]
> Not looking good on armhf. Test suite fails
> 
> ```
> <unknown> GET / => 404 (../src/http.c:128)

A couple of tests are expected to return 404. Try to increase the timeout in `test/meson.build` and see if it actually fails some test or manages to complete them.

**Comment by sergio-correia** [comment]
@cbiedl: could you try this updated version, please?

**Comment by cbiedl** [comment]
Looks fine here, build passes on armhf, requesting an advertisement works as expected.

One thing in the sources, though: `units/tangd.socket` is coverved by `.gitignore`, such a situation can lead to confusion and strange errors.

**Comment by sergio-correia** [comment]
> Looks fine here, build passes on armhf, requesting an advertisement works as expected.
> 

Thanks for testing. 

> One thing in the sources, though: `units/tangd.socket` is coverved by `.gitignore`, such a situation can lead to confusion and strange errors.

Good point. Looking into `.gitignore`, I see many entries related to `autotools`, that could be removed. I will remove `.socket` from there for now and clean it up more broadly in a follow-up PR.

**Review by ZelenyMartin — APPROVED** [review]

**Comment by rugk** [comment]
Just as a follow/heads-up:
> I will remove .socket from there for now and clean it up more broadly in a follow-up PR.

Did you actually do this, @sergio-correia? [I've checked your recent PRs](https://github.com/latchset/tang/pulls?q=is%3Apr+is%3Aclosed+author%3Asergio-correia+) and they all seem to be about something different.

**Comment by sergio-correia** [comment]
> Just as a follow/heads-up:
> 
> > I will remove .socket from there for now and clean it up more broadly in a follow-up PR.
> 
> Did you actually do this, @sergio-correia?
> [...]

Not yet. `.gitignore` still needs some clean up.

**Pull request merged**
