### PR TITLE
tests: unify tests

### PR DESCRIPTION
**Pull request by sergio-correia**
Let's try to not duplicate tests but instead reuse them across the
supported platforms.

### CODE REVIEW

**Comment by sergio-correia** [comment]
@hdholm: could you check if this works for you, please?

**Review by hdholm — CHANGES_REQUESTED** [review]
So overall this worked for me and I like the combined tests.  I did have one oddity.  My meson complains and bails out with
../tests/meson.build:36:8: ERROR: Arguments must be strings.
changing the 1 in that line to a string makes meson happy and everything seems to work once that change is made. i.e.,
  env.set('TANG_BSD', '1')

**Comment by hdholm** [comment]
And a typo (sadly originally mine) the 6553 in jot line should be 65536 in the new tests/helpers.

**Comment by sergio-correia** [comment]
> So overall this worked for me and I like the combined tests. I did have one oddity. My meson complains and bails out with
> ../tests/meson.build:36:8: ERROR: Arguments must be strings.
> changing the 1 in that line to a string makes meson happy and everything seems to work once that change is made. i.e.,
> env.set('TANG_BSD', '1')

Good catch, thanks. Fixed it here.

**Review by ZelenyMartin — APPROVED** [review]

**Pull request merged**
