### PR TITLE
Readme updates

### PR DESCRIPTION
**Pull request by hdholm**
Update README.md to account for recent llhttp build changes and the availability of packaged versions for FreeBSD.

### CODE REVIEW

**Comment by hdholm** [comment]
My original thinking had been to update the README to show llhttp as the required library.  But, of course, the Debian-based distros don't have it and it looks like CentOS 7 and CentOS Stream 8 don't either.  CentOS Stream 9 is being built with http-parser, although llhttp is available in EPEL 9.  So, now I'm thinking maybe the README should be adjusted to be clearer that it works with both.  I was just trying to make it reflect recent events; I don't have a preference if someone else changes it.  I'm certainly also happy to make the adjustments to the PR if that's what's preferred.

**Review by sarroutbi — APPROVED** [review]
Thanks for your change. In general, it LGTM. Requesting some minimum changes to distinguish between distributions

**Review by sarroutbi — CHANGES_REQUESTED** [review]
Thanks for your changes. As you commented, please, change to include both dependencies according to the kind  of distribution. Something like this would be enough:

Tang requires a few other software libraries:
- CentOS / Debian based distributions:
1. https-parser >= 2.8.0
2. systemd
3. jose
- Rest of distributions:
1. llhttp - ...
2. systemd
3. jose

**Review by sarroutbi — APPROVED** [review]
Changes LGTM

**Review by sergio-correia — APPROVED** [review]

**Pull request merged**
